'use strict';

const { fetchPRsForRepo, fetchReviews, approvePR, mergePR, createComment, deleteBranch } = require('./github-api');
const {
  hasChangesRequested,
  checkPRAge,
  daysSince
} = require('./filters');

async function processPR(github, core, pr, config, releaseBranch) {
  const result = { repo: pr.repo, pr: pr.data, reason: null };

  if (pr.data.head.ref !== releaseBranch) return null;

  if (pr.data.base.ref !== config.baseBranch) return null;

  if (!checkPRAge(pr.data, config.maxAgeDays)) {
    result.reason = `Too old (${daysSince(pr.data.created_at)} days)`;
    return result;
  }

  let reviews;
  try {
    reviews = await fetchReviews(github, config.org, pr.repo, pr.data.number);
  } catch (e) {
    result.reason = `Failed to fetch reviews: ${e.message}`;
    return result;
  }

  if (hasChangesRequested(reviews)) {
    result.reason = 'Changes requested';
    return result;
  }

  if (config.dryRun) {
    core.info(`🔍 [Dry Run] Would merge ${config.org}/${pr.repo}#${pr.data.number}`);
    return { pending: true, repo: pr.repo, pr: pr.data };
  }

  try {
    await approvePR(github, config.org, pr.repo, pr.data.number);
    core.info(`✅ Approved ${config.org}/${pr.repo}#${pr.data.number}`);
    
  } catch (e) {
     const apiMessage = e?.response?.data?.message;
     const apiErrors = e?.response?.data?.errors || [];
     const errMsg = apiMessage || e?.message || String(e);
     const isSelfApproval =
       /approve your own pull request/i.test(errMsg) ||
       apiErrors.some(err => /approve your own pull request/i.test(err.message || ''));

     if (isSelfApproval) {
      core.warning(`Skipping self-approval for ${config.org}/${pr.repo}#${pr.data.number} — proceeding to merge`);
     } else {
      result.reason = `Approve failed: ${errMsg}`;
       core.warning(`Failed to approve ${config.org}/${pr.repo}#${pr.data.number}: ${errMsg}`);
       return result;
     }
  }

  try {
    const runUrl = `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;
    const comment = [
      `This PR was automatically merged as part of the **${config.month}** monthly release.`,
      '',
      `> _Auto-generated by the [Release PRs workflow run #${process.env.GITHUB_RUN_ID}](${runUrl}) &nbsp;|&nbsp; Triggered by @${process.env.GITHUB_ACTOR}_`
    ].join('\n');
    await createComment(github, config.org, pr.repo, pr.data.number, comment);
  } catch (e) {
    core.warning(`Failed to post comment on ${config.org}/${pr.repo}#${pr.data.number}: ${e.message}`);
  }

  try {
    const mergeResult = await mergePR(
      github,
      config.org,
      pr.repo,
      pr.data.number,
      config.mergeMethod
    );
    core.info(`✅ Merged ${config.org}/${pr.repo}#${pr.data.number}`);

    const sourceBranch = pr.data.head.ref;
    try {
      await deleteBranch(github, config.org, pr.repo, sourceBranch);
      core.info(`🗑️ Deleted branch ${sourceBranch} in ${pr.repo}`);
    } catch (e) {
      core.warning(`Failed to delete branch ${sourceBranch} in ${pr.repo}: ${e.message}`);
    }

    return {
      merged: true,
      repo: pr.repo,
      pr: pr.data,
      sha: mergeResult.data.sha.slice(0, 7)
    };
  } catch (e) {
    result.reason = `Merge failed: ${e.message}`;
    core.warning(`Failed to merge ${config.org}/${pr.repo}#${pr.data.number}: ${e.message}`);
    return result;
  }
}

async function scanRepo(github, core, config, repo, releaseBranch) {
  core.info(`Scanning ${config.org}/${repo} ...`);

  let prs;
  try {
    prs = await fetchPRsForRepo(github, core, config.org, repo);
  } catch (e) {
    return { merged: [], pending: [], skipped: [], errors: [{ repo, error: e.message }] };
  }

  const merged = [];
  const pending = [];
  const skipped = [];

  for (const pr of prs) {
    const result = await processPR(github, core, { repo, data: pr }, config, releaseBranch);
    if (!result) continue;

    if (result.pending) {
      pending.push({
        repo: result.repo,
        number: result.pr.number,
        title: result.pr.title,
        branch: result.pr.head.ref
      });
    } else if (result.merged) {
      merged.push({
        repo: result.repo,
        number: result.pr.number,
        title: result.pr.title,
        branch: result.pr.head.ref,
        sha: result.sha
      });
    } else {
      skipped.push({
        repo: result.repo,
        number: result.pr.number,
        reason: result.reason
      });
    }
  }

  return { merged, pending, skipped, errors: [] };
}

module.exports = { processPR, scanRepo };
